version: '3.8'

services:
  nestjs-school-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_school_api_ctr
    environment:
      PORT: ${PORT}
    ports:
      - 5000:${PORT}
