name: CI with GitHub action

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn' # <- Replace 'npm' with 'yarn' or vice versa, depending on what package manager you use
    - run: rm -rf node_modules && yarn install --frozen-lockfile # <- An alternative for 'npm ci'
    - run: yarn build # <- DO NOT replace this with 'yarn build --if-present' as the '--if-present' parameter is not recognized 
    #- run: yarn test # Currently fails with an error : "No tests found, exiting with code 1"

  login:
    needs: node
    runs-on: ubuntu-latest

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
  
  build-push:
    needs: login
    runs-on: ubuntu-latest
    steps:
      - name: Build a Docker image
        run: docker build . -t ${{secrets.DOCKER_USERNAME}}/nestjs-school-api:latest
      
      - name: Push the Docker image to DockerHub
        run: docker push ${{secrets.DOCKER_USERNAME}}/nestjs-school-api:latest
        # uses: docker/build-push-action@v2
        # with:
        #   context: .
        #   file: Dockerfile
        #   push: true
        #   tags: ${{secrets.DOCKER_USERNAME}}/nestjs-school-api:latest